var PersonalityInsightsV3 = require('watson-developer-cloud/personality-insights/v3');
var watsonCredentials = require('../watson_config');

var personality_insights = new PersonalityInsightsV3({
  username: watsonCredentials.username,
  password: watsonCredentials.password,
  version_date: '2016-10-19'
});

personality_insights.profile({
  text: 'Usain Bolt and Caster Semenya are two extraordinary athletes dominating their sports, but the disparity in how they are treated by the media reveals the pervasiveness of sexism in our society, and the complex ways this intersects with racism too. When Usain Bolt wins the triple triple he is “flawless”, “untouchable”, no one is upset and no one accuses him of being an “unnatural” man. There is of course the phenomenon of trying to explain away black success rather than celebrate it, often through interrogating the physiology of the black body rather than attributing success to the mind (Olympic bodies always defy “normal” expectations, but what I find astounding is the determination and drive necessary to achieve that level of success), but Usain Bolt is at least allowed to be successful.
 
Caster Semenya on the other hand, isn’t. Women are still seen and defined as secondary to men, as lesser than men or as an “incomplete” man, and this really is how it’s done since science has never been able to summarise humanity into two neat little categories, and this problem of binary oppressive logic is compounded for BME women. Nowhere is this truer than in sport. When Caster Semenya finishes two seconds ahead of the competition (just like Bolt), she’s suddenly not a woman, because women aren’t allowed to be that successful, she defies expectation, more than that, she defies definition. Rather than interrogate the definitions though, we seem intent on interrogating her.
 
Semenya’s success can only be challenged in a society in which a binary sex-system simplifies reality, and when this system is premised on women being “naturally” inferior to men. If you are a man and you defy this system you are celebrated, but if you are a woman and you defy this system, the best you can ever expect to be is a man. This is the message that Semenya’s story sends to us all, and it’s a message we have heard for a very long time.
 
The categories we place on the world are not neutral. Social scientists have of course known this for a while. Words, concepts and ideas shape and inform the world we live in, we construct things around the ideas we have of them – and this interaction between language and the world is a complex and difficult one, involving “feedback loops”. It’s a debate that anyone commenting on sport segregation or “black physiology” should look into in order to be able to make the sort of nuanced analysis necessary for the complex questions of sex and race. Many wade into these debate with no real knowledge of science and biology, and even less knowledge of how language operates, and an astonishing percentage of the people who weigh in to uphold sex segregation or “explain” black success are white men, and that point is significant. 
 
In the past, the International Association of Athletics Federations (IAAF) and the International Olympic Committee (IOC) have forced athletes like Semenya to medically alter their natural testosterone levels in order to compete. Instead of celebrating Semenya’s athleticism as we have done with Bolt, her win in the 800m has reignited the debate around how we can properly police sex categorisation, to the detriment of those we currently define as women as well as those who resist these simplistic categorisations altogether.
 
When we regulate hormone levels under the guise of “unfair advantage” we are actually using the concept of sex to make an intervention in the world, in order to construct reality into the image we have of it. This same phenomena occurs with intersex babies, again showing the intersections or racism and sexism. When other cultures alter the genitalia of children we consider it genital mutilation, but when Western doctors construct the genitalia of intersex babies to reflect the binary sex-system that we hold dear, that’s just “cold hard science”. These questions aren’t easy, but philosophy and ethics can help light the way.
 
Are we also expected to believe that sexuality and skin colour have nothing to do with Semenya’s treatment in the media? The fact that Semenya is married to a woman is an irrelevant fact that the media constantly highlights, showing how our common narratives around sex still falsely tie this to our sexuality and gender performances. The implication is that if you are a lesbian, your status as a woman is more questionable, and this is made even worse by the fact that Semenya is a black woman. We know that black bodies have been scrutinised and fetishized for centuries. Those of us who study this need not be reminded of Saartjie Baartman, a black woman whose body was paraded in a “freak show” before white spectators in 19th century Europe. The question of “normal” black bodies has always weighed more heavily on women. History is important, it informs and resonates in the present, we should learn from it in order to create a more ethical world, particularly when we are white and male. Would Semenya’s body receive the same media criticism if she were a white women performing her gender role correctly? I would hazard a guess that the question of whether she was “really a woman” (when no such clear category exists), would never have been posed in the first place. Would a 6th placed black woman’s tears over the success of a white women have been reported as widely and as compassionately as Lyndsey Sharp’s?
 
The idea that we can, or even should, regulate “unfair advantage” in competitive sports is already an absurdity, acknowledgement of which brings about huge levels of unnecessary discomfort. Do we ban people with access to better funding, better diets and better coaches? Perhaps we should regulate the amount of support that athletes across the world receive. Should we ban people from countries that aren’t currently ravaged by war? There are obvious reasons why the global superpower dominates the Olympic medals table and other countries, such as Syria do not.
 
Society appears to be somewhat agreed on banning doping and the use of performance enhancing drugs (and presumably in the future, performance enhancing technology or gene manipulation too), but again this seems to come down to the sanctity of the “human”, and perhaps this is a way of holding onto an impossible ideal of the “natural” in a world where such distinctions are being eroded at an alarming rate. A world where bodily integrity is increasingly questioned through the prevalence of drugs (legal or otherwise) and medical interventions relating to aesthetics, performance, identity or subjectivity become more commonplace, not to mention the neurological changes occurring in an age of information, technology, marketing, precarity and stress. The current work on the “post-human” in the (post)humanities can help us navigate these 21st century ethical problems. Who knows what the Olympic games will look like in 100 years. Clearly it will be different, change is the only thing we can ever be sure of, but we should use the most interesting concepts and debates in both the social and hard sciences, in conversation with each other, to inform the ethical direction we want these debates to go in. We shouldn’t be scared of these debates, but we should make sure we are asking the right questions instead of interrogating and policing the “wrong” bodies.
Add Comment Co',
  consumption_preferences: true
  },
  function (err, response) {
    if (err)
      console.log('error:', err);
    else
      console.log(JSON.stringify(response, null, 2));
});